all: msdfgen_lib.dll

msdfgen_lib.dll: msdfgen_lib.obj
	cl /LD /MD msdfgen_lib.obj "msdfgen\msdfgen.lib" "msdfgen\freetype\win32\freetype.lib"

msdfgen_lib.obj: msdfgen_lib.cpp
	cl /c /MD msdfgen_lib.cpp /I . /I "msdfgen\freetype\include" /I "msdfgen\include"

.PHONY: all
